# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 606)
        MainWindow.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -101, 821, 711))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_watch_data = QtWidgets.QFrame(self.frame)
        self.frame_watch_data.setGeometry(QtCore.QRect(10, 370, 441, 321))
        self.frame_watch_data.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"}")
        self.frame_watch_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_watch_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_watch_data.setObjectName("frame_watch_data")
        self.label_5 = QtWidgets.QLabel(self.frame_watch_data)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(140, 20, 161, 16))
        self.label_5.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.frame_watch_data)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(40, 50, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"color:white;\n"
"\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame_watch_data)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(160, 230, 141, 61))
        self.pushButton.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.frame_tim = QtWidgets.QFrame(self.frame)
        self.frame_tim.setGeometry(QtCore.QRect(460, 380, 311, 181))
        self.frame_tim.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"}")
        self.frame_tim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tim.setObjectName("frame_tim")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_tim)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 40, 221, 31))
        self.textEdit_3.setStyleSheet("QTextEdit{\n"
"color:white;\n"
"border-radius:20px;\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(self.frame_tim)
        self.label_6.setGeometry(QtCore.QRect(46, 10, 191, 20))
        self.label_6.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_tim)
        self.textEdit_4.setGeometry(QtCore.QRect(30, 120, 221, 31))
        self.textEdit_4.setStyleSheet("QTextEdit{\n"
"color:white;\n"
"border-radius:20px;\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame_tim)
        self.label_7.setGeometry(QtCore.QRect(46, 90, 191, 20))
        self.label_7.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_statu_main = QtWidgets.QFrame(self.frame)
        self.frame_statu_main.setGeometry(QtCore.QRect(0, 100, 781, 16))
        self.frame_statu_main.setToolTipDuration(-1)
        self.frame_statu_main.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"\n"
"}")
        self.frame_statu_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_statu_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_statu_main.setObjectName("frame_statu_main")
        self.label_8 = QtWidgets.QLabel(self.frame_statu_main)
        self.label_8.setGeometry(QtCore.QRect(-30, -50, 351, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_statu_main)
        self.frame_2.setGeometry(QtCore.QRect(40, 20, 241, 171))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    background-color: rgb(63, 63, 63);\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(60, 20, 101, 20))
        self.label_9.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_10.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(110, 50, 101, 20))
        self.label_11.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(110, 100, 101, 20))
        self.label_12.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.label_13.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.frame_3 = QtWidgets.QFrame(self.frame_statu_main)
        self.frame_3.setGeometry(QtCore.QRect(440, 0, 341, 581))
        self.frame_3.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    background-color: rgb(63, 63, 63);\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(110, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 321, 511))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.label_3 = QtWidgets.QLabel(self.frame_statu_main)
        self.label_3.setGeometry(QtCore.QRect(230, 560, 181, 31))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.state = QtWidgets.QLabel(self.frame_statu_main)
        self.state.setGeometry(QtCore.QRect(350, 560, 61, 31))
        self.state.setStyleSheet("")
        self.state.setObjectName("state")
        self.label_8.raise_()
        self.frame_3.raise_()
        self.label_3.raise_()
        self.state.raise_()
        self.frame_2.raise_()
        self.frame_get_Link = QtWidgets.QFrame(self.frame)
        self.frame_get_Link.setGeometry(QtCore.QRect(10, 110, 421, 241))
        self.frame_get_Link.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"}")
        self.frame_get_Link.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_get_Link.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_get_Link.setObjectName("frame_get_Link")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_get_Link)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 180, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame_get_Link)
        self.label.setGeometry(QtCore.QRect(-30, -50, 351, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame_get_Link)
        self.label_4.setGeometry(QtCore.QRect(110, 50, 161, 16))
        self.label_4.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_get_Link)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 80, 401, 71))
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
"color:white;\n"
"\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.frame_save = QtWidgets.QFrame(self.frame)
        self.frame_save.setGeometry(QtCore.QRect(440, 120, 311, 71))
        self.frame_save.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"border:3px solid white;\n"
"border-radius:20px;\n"
"}")
        self.frame_save.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save.setObjectName("frame_save")
        self.label_2 = QtWidgets.QLabel(self.frame_save)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 101, 20))
        self.label_2.setStyleSheet("QLabel{\n"
"color:white;\n"
"border:0px solid white;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.save_txt = QtWidgets.QCheckBox(self.frame_save)
        self.save_txt.setGeometry(QtCore.QRect(20, 130, 70, 17))
        self.save_txt.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"\n"
"}")
        self.save_txt.setTristate(False)
        self.save_txt.setObjectName("save_txt")
        self.save_json = QtWidgets.QCheckBox(self.frame_save)
        self.save_json.setGeometry(QtCore.QRect(190, 130, 70, 17))
        self.save_json.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"\n"
"}")
        self.save_json.setObjectName("save_json")
        self.save_data = QtWidgets.QCheckBox(self.frame_save)
        self.save_data.setGeometry(QtCore.QRect(110, 30, 70, 17))
        self.save_data.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"\n"
"}")
        self.save_data.setObjectName("save_data")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 620, 161, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color:white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.raise_()
        self.frame_watch_data.raise_()
        self.frame_tim.raise_()
        self.frame_get_Link.raise_()
        self.frame_save.raise_()
        self.frame_statu_main.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "x pathyleriniz"))
        self.pushButton.setText(_translate("MainWindow", "watch data"))
        self.label_6.setText(_translate("MainWindow", "delay update time"))
        self.label_7.setText(_translate("MainWindow", "update count"))
        self.label_8.setText(_translate("MainWindow", "istediniz datanin xpatini asssagiya yapıstırın daha\n"
" fazla x path icin arasina ! koyunuz"))
        self.label_9.setText(_translate("MainWindow", "STATUS"))
        self.label_10.setText(_translate("MainWindow", "update ="))
        self.label_11.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "lates time ="))
        self.label_14.setText(_translate("MainWindow", "CONSOLE"))
        self.label_15.setText(_translate("MainWindow", "LOG"))
        self.label_3.setText(_translate("MainWindow", "data watcher run state="))
        self.state.setText(_translate("MainWindow", "false"))
        self.pushButton_2.setText(_translate("MainWindow", "get link"))
        self.label.setText(_translate("MainWindow", "istediniz datanin xpatini asssagiya yapıstırın daha\n"
" fazla x path icin arasina ! koyunuz"))
        self.label_4.setText(_translate("MainWindow", "web site link"))
        self.label_2.setText(_translate("MainWindow", "save file type"))
        self.save_txt.setText(_translate("MainWindow", ".txt"))
        self.save_json.setText(_translate("MainWindow", "json"))
        self.save_data.setText(_translate("MainWindow", "save data"))
        self.pushButton_3.setText(_translate("MainWindow", "last settings"))
